apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Rollout を kustomize で扱うための設定を components にまとめる
# https://argo-rollouts.readthedocs.io/en/latest/features/kustomize/

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml
  - rollout-transform.yaml

openapi:
  path: https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_all_k8s_kustomize_schema.json
